/**
 * Low-resolution twins of the showcase images, keyed by the original path.
 *
 * Generated by `scripts/build-image-variants.mjs` — do not edit by hand.
 */
export const LOW_RES_IMAGES = Object.freeze({
  "images/card-citybike.png": "images/lq/card-citybike.jpg",
  "images/card-innodragon.png": "images/lq/card-innodragon.jpg",
  "images/card-innophish.png": "images/lq/card-innophish.jpg",
  "images/case-dragon-hero.png": "images/lq/case-dragon-hero.jpg",
  "images/comp.png": "images/lq/comp.jpg",
  "images/dragon.png": "images/lq/dragon.jpg",
  "images/img-1.png": "images/lq/img-1.jpg",
  "images/img-2.png": "images/lq/img-2.jpg",
  "images/img-3.png": "images/lq/img-3.png",
  "images/macbook-248-17115.png": "images/lq/macbook-248-17115.png",
  "images/macbook-lid.png": "images/lq/macbook-lid.png",
  "images/macbook.png": "images/lq/macbook.png",
  "images/phish.png": "images/lq/phish.jpg"
});
