/**
 * Low-resolution previews of the showcase images, keyed by the original path.
 *
 * Generated by `scripts/build-image-variants.mjs` — do not edit by hand.
 */
export const LOW_RES_IMAGES = Object.freeze({
  "images/card-citybike.png": "images/lq/card-citybike.webp",
  "images/card-default.png": "images/lq/card-default.webp",
  "images/card-innodragon.png": "images/lq/card-innodragon.webp",
  "images/card-innophish.png": "images/lq/card-innophish.webp",
  "images/case-dragon-hero.png": "images/lq/case-dragon-hero.webp",
  "images/comp.png": "images/lq/comp.webp",
  "images/dragon.png": "images/lq/dragon.webp",
  "images/img-1.png": "images/lq/img-1.webp",
  "images/img-2.png": "images/lq/img-2.webp",
  "images/img-3.png": "images/lq/img-3.webp",
  "images/img-bg.png": "images/lq/img-bg.webp",
  "images/macbook-248-17115.png": "images/lq/macbook-248-17115.webp",
  "images/macbook-lid.png": "images/lq/macbook-lid.webp",
  "images/macbook.png": "images/lq/macbook.webp",
  "images/me.png": "images/lq/me.webp",
  "images/phish.png": "images/lq/phish.webp",
  "images/stickers/anime.png": "images/lq/stickers/anime.webp",
  "images/stickers/seal.png": "images/lq/stickers/seal.webp"
});
